server:
  port: 8087
spring:
  application:
    name: user-service
  datasource:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
      lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
      lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
      prefer-ip-address: true
      ip-address: 127.0.0.1
      instance-id: ${spring.application.name}:${server.port}
mybatis:
  type-aliases-package: com.leyou.user.pojo

rabbitmq:
      host: 192.168.0.152
      username: admin
      password: 123456
      virtual-host: /leyou

leyou:
  code:
     time: 5
     admqExchange: ly.sms.exchange
     admqQuence: sms.verify.code

