server:
  port: 7001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zjh199311/leyou-manager.git
          search-paths: config-repo
          username: 1006332734@qq.com
          password: zjh196813
