server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /leyou
    username: admin
    password: 123456
    host: 192.168.0.154
  redis:
    host: 192.168.0.154
    port: 6379
leyou:
  sms:
    accessKeyId: LTAIUbauumGulkPj
    accessKeySecret: LM4H8TV0aOapYmKV7LVlxYq1rolCNm
    templateCode: SMS_172881816 #短信模板ID
    signName: 倪的菜注册 # 签名名称
