server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5

  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1


zuul:
  prefix: /api
  retryable: true
  routes:
    item-service: /item/**  # 将商品微服务映射到/item/**
    user-service: /user/**  # 用户微服务
    auth-service: /auth/**  # 授权服务
    cart-service: /cart/**  # 购物车服务
    order-service: /order-service/**
    upload-service:    #上传图片服务
      path: /upload/**
      service: upload-service
      strip-prefix: false
    search-service: /search/**  # 搜索微服务
  sensitive-headers:     #所有敏感头都添加
  add-host-header: true  #添加host头信息

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000

ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 0 # 同一实例的重试次数

leyou:
  getway:
     pubKeyPath: D:\\Git\\rsa\\rsa.pub #公钥地址
     cookieName: LY_TOKEN # cookie的名字
  filter:
     allowPaths:
        - /api/auth
        - /api/search
        - /api/user/register
        - /api/user/check
        - /api/user/code
        - /api/item