server:
  port: 8089

spring:
  application:
    name: cart-service
  rabbitmq:
      virtual-host: /leyou
      username: admin
      password: 123456
      host: 192.168.0.154
  redis:
      host: 192.168.0.154
      port: 6379
eureka:
    client:
      service-url:
          defaultZone: http://127.0.0.1:10086/eureka
      registry-fetch-interval-seconds: 10   #服务消费者启动会检测eureka.client.fetch-registry=true参数的值，如果为true从Eureka Server服务的列表只读备份，然后缓存在本地，并且每隔30秒会重新获取并更新数据
    instance:
      lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
      lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
      prefer-ip-address: true
      ip-address: 127.0.0.1
      instance-id: ${spring.application.name}:${server.port}

leyou:
  cart:
     pubKeyPath: D:\\Git\\rsa\\rsa.pub #公钥地址
     cookieName: LY_TOKEN # cookie的名字