server:
  port: 8082


spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  rabbitmq:
      host: 192.168.0.152
      username: admin
      password: 123456
      virtual-host: /leyou
      template:
        retry:
          enabled: true
          initial-interval: 10000ms
          max-interval: 30000ms
          multiplier: 2
        exchange: leyou.item.exchange
      publisher-confirms: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
      lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
      lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
      prefer-ip-address: true
      ip-address: 127.0.0.1
      instance-id: ${spring.application.name}:${server.port}

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
     ##开启驼峰映射
    map-underscore-to-camel-case: true
  type-aliases-package: com.leyou.item.pojo
  mapper-locations:
     - classpath:mybatis/mapping/*.xml
  config-location: classpath:mybatis/mybatis.cfg.xml



